apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
  labels:
    app: ollama
spec:
  ports:
  - name: http
    protocol: TCP
    port: 11434
    targetPort: 11434
  selector:
    app: ollama
  type: ClusterIP